// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS_System;

#nullable disable

namespace POS_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241027014628_InitianCreate")]
    partial class InitianCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("POS_System.Classes.POSItem", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemID");

                    b.ToTable("POSItems");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            Name = "Big Mac",
                            Price = 6.50m
                        },
                        new
                        {
                            ItemID = 2,
                            Name = "Medium Fries",
                            Price = 3.20m
                        },
                        new
                        {
                            ItemID = 3,
                            Name = "Coke",
                            Price = 4.50m
                        },
                        new
                        {
                            ItemID = 4,
                            Name = "Coke No Sugar",
                            Price = 4.50m
                        },
                        new
                        {
                            ItemID = 5,
                            Name = "Oreo McFlurry",
                            Price = 4.75m
                        },
                        new
                        {
                            ItemID = 6,
                            Name = "M&M McFlurry",
                            Price = 4.75m
                        });
                });

            modelBuilder.Entity("POS_System.Classes.POSUser", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasDiscriminator<int>("UserType");
                });

            modelBuilder.Entity("POS_System.Classes.Crew", b =>
                {
                    b.HasBaseType("POS_System.Classes.POSUser");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue(0);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Name = "Ronald McDonald",
                            Password = "password",
                            UserType = 0
                        });
                });

            modelBuilder.Entity("POS_System.Classes.Manager", b =>
                {
                    b.HasBaseType("POS_System.Classes.POSUser");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue(2);

                    b.HasData(
                        new
                        {
                            UserID = 3,
                            Name = "Grimace",
                            Password = "password",
                            UserType = 0
                        });
                });

            modelBuilder.Entity("POS_System.Classes.TeamLead", b =>
                {
                    b.HasBaseType("POS_System.Classes.POSUser");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            UserID = 2,
                            Name = "The Hamburgler",
                            Password = "password",
                            UserType = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
